from typing import Protocol

class FactContractValidator(Protocol):
    def validate(self, fact) -> None: ...
    def is_reference(self, value: str) -> bool: ...
    def is_path(self, value: str) -> bool: ...
