from typing import Protocol
from app.projects.domain.project import Project

class ProjectRepository(Protocol):
    def list(self) -> list[Project]: ...
    def get(self, project_id: str) -> Project | None: ...
    def find_path(self, path: str) -> Project | None: ...
    def add(self, project: Project) -> Project: ...

class ProjectPathResolver(Protocol):
    def resolve(self, value: str) -> str: ...
