from typing import Protocol
from app.evaluations.domain.evaluator import Evaluator
from app.evaluations.domain.execution import EvaluatorExecution
from app.facts.domain.provenance import ProducerExecution
from app.scans.domain.scan import Scan
from app.snapshots.domain.snapshot import Snapshot

class ScanRepository(Protocol):
    def list(self, project_id: str) -> list[Scan]: ...
    def add(self, scan: Scan) -> Scan: ...
    def get(self, project_id: str, scan_id: str) -> Scan | None: ...
    def complete(self, scan_id: str) -> Scan: ...

class AnalysisFacts(Protocol):
    def add(self, scan_id: str, evaluator_id: str, facts) -> None: ...
    def query(self, scan_id: str, **filters) -> list[dict]: ...
    def revision(self, scan_id: str) -> int: ...
    def has_reference(self, scan_id: str, root: str) -> bool: ...
    def neighbor(self, scan_id: str, root: str, relation: str, direction: str,
                 after: str = '') -> tuple[str, dict] | None: ...

class AnalysisProvenance(Protocol):
    """Recorded before the facts: their snapshot and producer executions are checked against it."""
    def record_snapshot(self, scan_id: str, snapshot: dict) -> None: ...
    def record_execution(self, scan_id: str, execution: ProducerExecution) -> None: ...

class EvaluationRunner(Protocol):
    def __call__(self, evaluator: Evaluator, snapshot: Snapshot, progress=None) -> EvaluatorExecution: ...
